# Generated by Django 3.0.14 on 2023-04-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('passwoed', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='savefile',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
